services:
  - type: web
    name: course-tracker-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn CourseTrackerApi.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: CourseTrackerApi.settings
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
