# Generated by Django 5.2.7 on 2025-10-06 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_subject_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': True},
        ),
    ]
