# Generated by Django 5.2.7 on 2025-10-07 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_subject_options_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': True},
        ),
    ]
